### ISSUE TITLE
Unable to import environment other than localhost

### ISSUE THREAD

**Issue by kindlednotes** [matt-ball/postman-cli#31]
I have two environment, localhost and heroku. Every time I run pm bootstrap, only localhost environment is getting retrieved in IDE.

**Comment by matt-ball** [comment]
Hi @kindlednotes - thanks for raising an issue. Right now the CLI only supports you sync'ing and updating 1 environment. But you've given me an idea, so watch this space 😄

**Comment by kindlednotes** [comment]
Hi,

Thanks for your response. I would like to know if we are also able run this
script from IDE as a project.

Thanks,
Tania Choudhury

**Comment by matt-ball** [comment]
Yes, if you use `postman sync` it'll update the postman_collection.json file for you. You can use that with Newman https://github.com/postmanlabs/newman

**Comment by matt-ball** [comment]
Hey @kindlednotes - please try 0.1.1 - you may have to start from scratch. You can select multiple environments now when you run `postman setup`. Feel free to open another issue if you run into trouble!
